# Generated by Django 4.0.2 on 2022-06-11 23:10

from django.db import migrations, models
import django.db.models.deletion
import premiumsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_name', models.CharField(help_text='Введите цвет на англ.', max_length=200, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='iPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_name', models.CharField(db_index=True, max_length=150, verbose_name='Название моделей iPhone')),
            ],
            options={
                'verbose_name': 'iPhone',
                'verbose_name_plural': 'iPhone',
                'ordering': ['iphone_name'],
            },
        ),
        migrations.CreateModel(
            name='MacBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macbook_name', models.CharField(db_index=True, max_length=150, verbose_name='Название моделей MacBook')),
            ],
            options={
                'verbose_name': ' Модели MacBook',
                'verbose_name_plural': ' Модели MacBook',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_info', models.CharField(help_text='Введите память в формате ...гб', max_length=100)),
            ],
            options={
                'verbose_name': 'Объем памяти',
                'verbose_name_plural': 'Объем памяти',
            },
        ),
        migrations.CreateModel(
            name='Model_iMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imac_model', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'iMac',
                'verbose_name_plural': 'iMac',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_os', models.CharField(help_text='Введите название Mac OS', max_length=200)),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционная система',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, null=True, verbose_name='Название Региона')),
            ],
            options={
                'verbose_name': 'Регионы',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='UsedPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_phone', models.ImageField(blank=True, upload_to='photos_used/%Y/%m/%d')),
                ('about_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('availability_phone', models.BooleanField(default=False)),
                ('colors_name', models.ForeignKey(help_text='Выберите цвет', on_delete=django.db.models.deletion.CASCADE, to='premiumsite.allcolors')),
                ('iphone_name', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.iphone')),
                ('memory_info', models.ForeignKey(help_text='Выберите память', on_delete=django.db.models.deletion.CASCADE, to='premiumsite.memory')),
                ('region_name', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.region')),
            ],
            options={
                'verbose_name': 'Б/У Аппараты',
                'verbose_name_plural': 'Б/У Аппараты',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_phone', models.IntegerField(verbose_name='Стоимость')),
                ('photo_phone', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото файлы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('y', 'В наличии'), ('n', 'Нет в наличии')], default='В наличии', max_length=10)),
                ('new_or_used', models.BooleanField(default=True, verbose_name='Новый')),
                ('colors_name', models.ForeignKey(help_text='Выберите цвет', on_delete=django.db.models.deletion.PROTECT, to='premiumsite.allcolors', verbose_name='Цвет')),
                ('iphone_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.iphone', verbose_name='Название')),
                ('memory_info', models.ForeignKey(help_text='Выберите память', on_delete=django.db.models.deletion.PROTECT, to='premiumsite.memory', verbose_name='Память')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premiumsite.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Новые iPhone',
                'verbose_name_plural': 'Новые iPhone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewMacBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_macbook', models.CharField(max_length=100, null=True, verbose_name='Год')),
                ('photo_phone', models.ImageField(blank=True, upload_to='photos_imac/%Y/%m/%d', verbose_name='Фото')),
                ('retina_lcd', models.BooleanField(default=True, null=True, verbose_name='Ретина')),
                ('diagonal', models.CharField(blank=True, max_length=150, null=True, verbose_name='Диагональ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии')),
                ('chip', models.CharField(max_length=100, null=True, verbose_name='Процессор')),
                ('availability_mac', models.BooleanField(choices=[('y', 'В наличии'), ('n', 'Нет в наличии')], default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('colors_name', models.ForeignKey(help_text='Выберите цвет', on_delete=django.db.models.deletion.CASCADE, to='premiumsite.allcolors', verbose_name='Цвет')),
                ('macbook_name', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.macbook', verbose_name='Модель')),
                ('memory_info', models.ForeignKey(help_text='Выберите память', on_delete=django.db.models.deletion.CASCADE, to='premiumsite.memory', verbose_name='Память')),
                ('operating_system', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.operatingsystem', verbose_name='Оперционная система')),
                ('region_name', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.region', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'MacBook',
                'verbose_name_plural': 'MacBook',
                'ordering': ['-macbook_name'],
            },
        ),
        migrations.CreateModel(
            name='iMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_imac', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=150, null=True, verbose_name=premiumsite.models.Region)),
                ('model_id', models.CharField(max_length=155)),
                ('articles', models.CharField(max_length=155)),
                ('photo_phone', models.ImageField(blank=True, upload_to='photos_imac/%Y/%m/%d')),
                ('diagonal', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chip', models.CharField(max_length=100, null=True)),
                ('new_or_used', models.BooleanField(default=True, verbose_name='Новый')),
                ('availability_phone', models.BooleanField(choices=[('y', 'В наличии'), ('n', 'Нет в наличии')], default=True, verbose_name='В наличии')),
                ('colors_name', models.ForeignKey(help_text='Выберите цвет', on_delete=django.db.models.deletion.PROTECT, to='premiumsite.allcolors')),
                ('imac_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premiumsite.model_imac')),
                ('memory_info', models.ForeignKey(help_text='Выберите память', on_delete=django.db.models.deletion.PROTECT, to='premiumsite.memory')),
                ('operating_system', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.operatingsystem')),
            ],
            options={
                'verbose_name': 'iMac',
                'verbose_name_plural': 'iMac',
                'ordering': ['-imac_model'],
            },
        ),
    ]
