# Generated by Django 4.0.2 on 2022-05-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiumsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imac',
            name='imac_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premiumsite.model_imac'),
        ),
    ]
