# Generated by Django 4.0.2 on 2022-05-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiumsite', '0002_alter_imac_imac_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiumsite.iphone', verbose_name='Название'),
        ),
    ]
